spring.datasource.url=jdbc:postgresql://dpg-dabvlv2jnfac73efaeu0-a.ohio-postgres.render.com:5432/vmcdb
spring.datasource.username=vmcuser
spring.datasource.password=GnAbRtWJNeV2sU8qnPiCUlypSyv1W9YI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
server.address=0.0.0.0