spring.datasource.url=jdbc:mysql://localhost:3306/vmcdb
spring.datasource.username=root
spring.datasource.password=Naresh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.address=0.0.0.0